import type { Metadata } from "next";
import { IBM_Plex_Sans, Poppins } from "next/font/google";
import "./globals.css";

import "./fonts/GeistMonoVF.woff";
import "./fonts/GeistVF.woff";

const ibmPlex = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-ibm-plex",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlex.variable} ${poppins.variable} antialiased bg-black min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
